# Generated by Django 3.1.5 on 2021-01-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BedClientAllocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_start_date', models.DateTimeField(verbose_name='date published')),
                ('allocation_end_date', models.DateTimeField(verbose_name='date published')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cura_app.bed')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cura_app.client')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cura_app.location'),
        ),
        migrations.CreateModel(
            name='AllocationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_start_date', models.DateTimeField(verbose_name='date published')),
                ('allocation_end_date', models.DateTimeField(verbose_name='date published')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cura_app.client')),
            ],
        ),
    ]
