# Generated by Django 3.1.5 on 2021-02-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cura_app', '0002_remove_bed_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationrequest',
            name='allocation_end_date',
            field=models.DateField(blank=True, verbose_name='Eind datum'),
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='allocation_start_date',
            field=models.DateField(verbose_name='Start datum'),
        ),
        migrations.AlterField(
            model_name='bedclientallocations',
            name='allocation_end_date',
            field=models.DateField(blank=True, verbose_name='Eind datum'),
        ),
        migrations.AlterField(
            model_name='bedclientallocations',
            name='allocation_start_date',
            field=models.DateField(verbose_name='Start datum'),
        ),
    ]
