# Generated by Django 3.1.5 on 2021-02-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cura_app', '0004_auto_20210201_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrequest',
            name='preferred_locations',
            field=models.ManyToManyField(to='cura_app.Location'),
        ),
    ]
